run:
  go: '1.22.2'
linters-settings:
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
linters:
  enable-all: true
  disable:
    - depguard
    - gci
    - testpackage
    - varnamelen
    - ireturn
    - wrapcheck
    - godot
    - exhaustruct
