CREATE TABLE m304 (
    id INT AUTO_INCREMENT PRIMARY KEY,
    uecs_id VARCHAR(255),
    mac_addr VARCHAR(255),
    dhcp_flg BOOLEAN,
    ip_addr VARCHAR(255),
    net_mask VARCHAR(255),
    defgw VARCHAR(255),
    dns VARCHAR(255),
    vender_name VARCHAR(255),
    node_name VARCHAR(255),
    `rly_0` INT NULL,
    `rly_1` INT NULL,
    `rly_2` INT NULL,
    `rly_3` INT NULL,
    `rly_4` INT NULL,
    `rly_5` INT NULL,
    `rly_6` INT NULL,
    `rly_7` INT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`rly_0`) REFERENCES uecs_devices (id) ON DELETE SET NULL,
    FOREIGN KEY (`rly_1`) REFERENCES uecs_devices (id) ON DELETE SET NULL,
    FOREIGN KEY (`rly_2`) REFERENCES uecs_devices (id) ON DELETE SET NULL,
    FOREIGN KEY (`rly_3`) REFERENCES uecs_devices (id) ON DELETE SET NULL,
    FOREIGN KEY (`rly_4`) REFERENCES uecs_devices (id) ON DELETE SET NULL,
    FOREIGN KEY (`rly_5`) REFERENCES uecs_devices (id) ON DELETE SET NULL,
    FOREIGN KEY (`rly_6`) REFERENCES uecs_devices (id) ON DELETE SET NULL,
    FOREIGN KEY (`rly_7`) REFERENCES uecs_devices (id) ON DELETE SET NULL
);