// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: m304.sql

package mysqlc

import (
	"context"
	"database/sql"
)

const createM304 = `-- name: CreateM304 :execlastid
INSERT INTO m304 (uecs_id, mac_addr, dhcp_flg, ip_addr, net_mask, defgw, dns, vender_name, node_name)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateM304Params struct {
	UecsID     string
	MacAddr    string
	DhcpFlg    bool
	IpAddr     sql.NullString
	NetMask    sql.NullString
	Defgw      sql.NullString
	Dns        sql.NullString
	VenderName string
	NodeName   sql.NullString
}

func (q *Queries) CreateM304(ctx context.Context, arg CreateM304Params) (int64, error) {
	result, err := q.db.ExecContext(ctx, createM304,
		arg.UecsID,
		arg.MacAddr,
		arg.DhcpFlg,
		arg.IpAddr,
		arg.NetMask,
		arg.Defgw,
		arg.Dns,
		arg.VenderName,
		arg.NodeName,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getM304FromID = `-- name: GetM304FromID :one
SELECT id, uecs_id, mac_addr, dhcp_flg, ip_addr, net_mask, defgw, dns, vender_name, node_name
FROM m304
WHERE id = ?
`

type GetM304FromIDRow struct {
	ID         int32
	UecsID     string
	MacAddr    string
	DhcpFlg    bool
	IpAddr     sql.NullString
	NetMask    sql.NullString
	Defgw      sql.NullString
	Dns        sql.NullString
	VenderName string
	NodeName   sql.NullString
}

func (q *Queries) GetM304FromID(ctx context.Context, id int32) (GetM304FromIDRow, error) {
	row := q.db.QueryRowContext(ctx, getM304FromID, id)
	var i GetM304FromIDRow
	err := row.Scan(
		&i.ID,
		&i.UecsID,
		&i.MacAddr,
		&i.DhcpFlg,
		&i.IpAddr,
		&i.NetMask,
		&i.Defgw,
		&i.Dns,
		&i.VenderName,
		&i.NodeName,
	)
	return i, err
}
